language: c
sudo: required
dist: trusty
install:
- sudo ./get-packages.sh
- ./get-libs.sh
script: make
after_success:
- tar -zcvf ci-build.tar.gz build
- curl -T ci-build.tar.gz -u $CURL_LOGIN $CURL_HOST
env:
  global:
  - secure: x/pYksSF1tgGJaFVHBZqsVW1B+N6CkFrD/JKw3yqoE3asdf6/PKdB35rC37ZYugfFUzIt4GnUeLW2KqUDgbo13ZU0Hn9OZBamGErFC+dRUsbgFznUua51YJrYX1TU10KDQvFH8O3EhcpzEnMgNA45BFRuCIL3gRQhEV2LqBO8nT4pOoeoW0rGIxdu+tYIp95EV1r182XzLylHDpYwXhv2VQizsQC8Pr6SUt3KrRdhcclkWSWOo+axq7HuIjyJRAYeD4Y+hNDnIrrwl4GaaVFqljCsIDoRkQpBvr/zWA6F24L4pQPdq4Qfk5sPe6pIAqOd0t/69tg0HJfR2hw0JR73Qnm83J0hXdzuJm/HKvxOsBHS02Zk0XYQEszz0C+qorYRcVyaLYxiFK/IiXtXIYwANuAV7Es/7+jhBb/tIcATHM8Ri3Ic8FNxwqw185O9m/78K69qF3WcPR4K0cs8argddhJHUdaSOxYShdZGvlqA0c0RKmsk3hTE492jUXAmtmlawC9LSEgQoYNfAlvdRYkW1DpenDwBJGZaO/VCYrfsTpA4WuHakU9Ed8UZBpa59K5fWExWr8+LUxf1Jo0FR/Hbf3Yd33SyNT95PulFCvt4or2t+Vo6xnWKON9IzHXl2lu+VjIJQUX0IA209Xv+MVW4JZAyou2mmbZUoiCcGnwu4U=
  - secure: V2b3fmJlXTn9diFPReJ02HSE5VoclJ8pds3I5TNGU0DNszhVLGlV6Dvb6M4EkVPnesxEn9QBRSecIEASXOHe2hx8vz4K5EohelHoo+4mNq1PaCL2pO8+0fcFSzqdeaW22x3HM7NgEXuGcxTinw7HlidYtV4HA2+jxsHznlnXGlMSs9nork14HEIdA1xaS6BzAYotqtxKXGSs/K8mRLvbg7FZg4np/KvrWNE+RtAT5Q5n5GbGueoGJmnBW6duCS9Mhy0npgBFU6Q8Q2cX+6HbzjxH2K8mKiO6XbIFyzcUjbfqUKC7goUKZmZ/YpJoCogASD9RKvcBrnlTbTDU1Y3V1F6e0e0o3HTj3deK92EUZ3Z2vi3N4uKHv5IFSkQkCW7vkJtSWHFeNz/pkVnLKHrNg6KrpuE7Xj8JqwsCNzANg3zlw4GMzb3COy/ABbRsk/7zVQfqLUvf3Fb86ccnkE3k1yEmkfv65/1gUucH/pBEnd7JpEwS1ynvlTTXrZD1KLIs+2DdAecr1RVgM4geW9XFgTn2tuVyiks9CpoLWqgtYPyT/dq3Y3tmp35S4yvtwrzk1G6Mclre/lFXt072+1oUoDZmyUB6fE1hd8YlmYCzfgRbFSYUxva28wHADsdiZJUTOZeKMQGlzVwCmF0gFZKHDrHoDSLdn7BGKNuLhHmbKME=
