language: c
sudo: required
dist: trusty
install:
- sudo apt-add-repository deb http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
- sudo apt-add-repository deb-src http://us-central1.gce.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
- sudo ./get-packages.sh
- ./get-libs.sh
script: make
